services:
  nodejs:
    container_name: app
    build: .
    ports:
      - "8000:3000"
  mysql:
    container_name: db
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=filevault
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.sql