services:
  nodejs:
    container_name: app
    platform: linux/amd64
    build: .
    ports:
      - "8080:3000"
  mysql:
    container_name: db
    platform: linux/amd64
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    env_file:
      - db/db.env
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.sql
  proxy:
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    image: nginx
    ports:
      - 80:80