apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: filevaultKeyvault
    userAssignedIdentityID: $CLIENT_ID
    objects: |
      array:
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: storage-account-key
          objectType: secret
        - |
          objectName: storage-container-name
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-table
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-root-password
          objectType: secret
    tenantId: $TENANT_ID
  secretObjects:
    - secretName: keyvault
      type: Opaque
      data:
        - key: storageAccountName
          objectName: storage-account-name
        - key: storageAccountKey
          objectName: storage-account-key
        - key: storageContainerName
          objectName: storage-container-name
        - key: dbHost
          objectName: db-host
        - key: dbTable
          objectName: db-table
        - key: dbUsername
          objectName: db-username
        - key: dbPassword
          objectName: db-password
        - key: dbRootPassword
          objectName: db-root-password
          