- name: Create Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
    - ansible.builtin
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: filevaultAnsible
      location: uksouth
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: filevaultAnsible
      name: filevaultVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: filevaultAnsible
      name: filevaultSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: filevaultVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: filevaultAnsible
      allocation_method: Static
      name: filevaultPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: filevaultAnsible
      name: filevaultNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: Website
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1000
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: filevaultAnsible
      name: filevaultNIC
      virtual_network: filevaultVnet
      subnet: filevaultSubnet
      security_group: filevaultNetworkSecurityGroup
      ip_configurations:
      - name: ipconfig1
        public_ip_address_name: filevaultPublicIP
      open_ports:
        - 22
        - 80
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: filevaultAnsible
      name: filevaultVM
      vm_size: Standard_DS1_v2
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: filevaultNIC
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest
      open_ports:
        - 22
        - 80
  - name: Add ip address to list of hosts
    add_host:
      name: '{{ output_ip_address.state.ip_address }}'
      group: filevault