name: Deploy

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v4
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_wrapper: false
        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
            enable-AzPSSession: true
        - name: Deploy azure resources
          run: sh bin/deploy-pods.sh
        - name: Wait 60 seconds for pods to deploy
          run: sleep 60
        - name: Destroy azure resources
          run: sh bin/destroy-pods.sh